---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
      - 192.168.0.1/28
    eth2:
      addresses:
      - 192.168.245.2/30
    eth3:
      addresses:
      - 192.168.255.2/30
      routes:
      - to: 0.0.0.0/0
        via: 192.168.255.1
    eth4:
      addresses:
      - 192.168.56.12/24